### ISSUE TITLE
investigate github actions to include CI/CD build on commits

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#526]
Since a while, Travis requires a fee and the `.travis.yml` file is not used. 
Instead github actions should be the option. Investigate how to set that up to run `sbt build` on each commit.

**Comment by fritjof-b** [comment]
I had a quick look over at https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions

The config file uses YAML-syntax. The jobs in the config file is run by a `runner` that can either be hosted on GitHub or on your own server. The code and binaries for the runner is found at: https://github.com/actions/runner

There was also a guide for migrating from Travis to GitHub Actions:
https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

From what I read it should be possible to do something like (maybe `on: [pull]` instead?):

```yaml
# there are more options than these
# we can specify branches that trigger
# events as well, etc...
name: Run SBT build
on: [push]
jobs:
   # add more jobs
  Build:
    runs-on: ubuntu-latest
    steps:
       - run: sbt build
       # add other steps
```
